server:
  port: 8080
spring:
  application:
        name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Sarwesh@1
  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true  # Use IP address instead of hostname
  client:
    fetch-registry: true   # Fetch registry from Eureka
    register-with-eureka: true  # Register this service with Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL of the Eureka server



